### ISSUE TITLE
SVG color

### ISSUE THREAD

**Issue by krionical** [PandaSekh/Jekyll-Podcaster#1]
I have been trying to change the SVG wave color to black. I can change the background to black. I cannot seem to change the wave into any color other than the blue. The whole svg disappears on firefox and chromium. I have used the url encode link to change it and it seems like any other color than the supplied blue is an issue. Am I missing something?

**Comment by PandaSekh** [comment]
I'm going to look into this as soon as possible

**Comment by PandaSekh** [comment]
Before the encoded url, in the url parameter in the scss, you have to insert this line: `data:image/svg+xml;utf8,`    

I added a note in the README to make it clearer.

**Comment by krionical** [comment]
I did that before and I don't remember it saying anything, but it did this time: [2020-11-06 14:30:02] ERROR `/assets/css/data:image/svg xml;utf8,<svg xmlns="http:/www.w3.org/2000/svg" viewBox="0 40 1440 320">\n  <path fill="#000000" fill-opacity="1" d="M0,160L48,176C96,192,192,224,288,229.3C384,235,480,213,576,176C672,139,768,85,864,90.7C960,96,1056,160,1152,165.3C1248,171,1344,117,1392,90.7L1440,64L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>\n</svg>' not found.

This is what it looks like "in code": 'data%3Aimage%2Fsvg%20xml%3Butf8%2C%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%2040%201440%20320%22%3E%0A%20%20%3Cpath%20fill%3D%22%23000000%22%20fill-opacity%3D%221%22%20d%3D%22M0%2C160L48%2C176C96%2C192%2C192%2C224%2C288%2C229.3C384%2C235%2C480%2C213%2C576%2C176C672%2C139%2C768%2C85%2C864%2C90.7C960%2C96%2C1056%2C160%2C1152%2C165.3C1248%2C171%2C1344%2C117%2C1392%2C90.7L1440%2C64L1440%2C0L1392%2C0C1344%2C0%2C1248%2C0%2C1152%2C0C1056%2C0%2C960%2C0%2C864%2C0C768%2C0%2C672%2C0%2C576%2C0C480%2C0%2C384%2C0%2C288%2C0C192%2C0%2C96%2C0%2C48%2C0L0%2C0Z%22%3E%3C%2Fpath%3E%0A%3C%2Fsvg%3E'

**Comment by krionical** [comment]
Never mind, I figured out what you meant. For anyone who makes this mistake in the future, omit the line in the notes for the encoded part, decode, re-encode, then add the data:image/svg+xml;utf8, back in before your newly re-encoded string.
