### ISSUE TITLE
How complex is to load the mp3 from external source?

### ISSUE THREAD

**Issue by jrichardsz** [PandaSekh/Jekyll-Podcaster#11]
Hi, I inspected and I saw that mp3 is hosted on github:

https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3

![image](https://user-images.githubusercontent.com/3322836/142771023-69fabe71-7e63-419f-9a85-3d8f8a18b159.png)

Since github is not for file hosting, is there an option to load the mp3 from another source?

If not, could you point me to the source code in order to add this feature? I'm not ruby developer but I will do my best :b

**Comment by PandaSekh** [comment]
Hi, the mp3 is not hosted on GitHub, I just took an example file from a website which hosts it on GitHub. 
When you create a post in the `_posts` folder, one of the parameters of the front matter is `file`, and there you put the url to the .mp3 file hosted wherever you want. 

You can see an example of it by opening one of the posts in the `_posts` folder.
