### ISSUE TITLE
How to add different icon for socials?

### ISSUE THREAD

**Issue by jy0000** [PandaSekh/Jekyll-Podcaster#12]
Hi! I wanted to add my LinkedIn to the socials in the side bar with the LinkedIn icon, but I'm not sure how to get the icon to show up
I have this
```
social:
  - {icon: 'envelope', type: "solid", link: 'mailto:j'}
  - {icon: 'linkedin', type: "solid", link: ""}
```
But it only shows up as this:
![image](https://user-images.githubusercontent.com/70900559/189548375-dd57d0ce-4aee-466b-9a84-ea7231698c34.png)

So in the gemspec i commented out the dependency specification
```
  spec.add_runtime_dependency "jekyll"#, "~> 4.0"

  spec.add_development_dependency "bundler"#, "~> 2.3.22" 
. 
```
Because when I tried replacing gem 'jekyll' with gem 'github-pages' but i get this error:
```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    bundler (~> 2.2.17) was resolved to 2.2.33, which depends on
      Ruby (>= 2.3.0)

    github-pages was resolved to 1, which depends on
      Ruby (~> 1.9.3)


In config I added 
```
url:  "61040-fa22.github.io" # Actual base url of the website
baseurl: "portfolio-jy0000"  
``

if I do baseurl: "/portfolio-jy0000" live reload works except the logo link leads to localhost:4000 instead of localhost:4000/portfolio-jy0000 and this seems to be due to index.html not changing automatically in line 60
```
<body><div id = "header">
    <h1><a href="http://localhost:4000">Joyce Yoon</a></h1>
    <div class = "wave">
    </div>
```
Live reload:
![image](https://user-images.githubusercontent.com/70900559/189581595-e46ee115-717e-44ce-8dc5-5818f8b0ab1f.png)

However in the deployed it looks like this
Deployed: ![image](https://user-images.githubusercontent.com/70900559/189581547-7c8066a2-a212-48e5-8de0-92985d20d277.png)

When I do baseurl: "portfolio-jy0000"   livereload does not work because it leads to localhost:4000portfolio-jy0000
But deployed looks better on the home page and the links lead to the right url:
![image](https://user-images.githubusercontent.com/70900559/189588649-aef5289b-5cf3-47a7-9385-c20d649fd7f8.png)

but https://61040-fa22.github.io/portfolio-jy0000/projects.html and about.html do not have any formatting
![image](https://user-images.githubusercontent.com/70900559/189588872-b62abb15-6339-47e2-b711-73b1e436a037.png)

And the links on the about.html and projects.html lead to doubling the url
Example click the main logo on projects.html -> https://61040-fa22.github.io/portfolio-jy0000/61040-fa22.github.io
Click projects link on projects.html -> https://61040-fa22.github.io/portfolio-jy0000/61040-fa22.github.io/portfolio-jy0000/projects.html

For my settings.yml I have the links as 
```
pages:
  - {name: 'About', link: 'about.html'}
  - {name: 'Projects', link: 'projects.html'}
  - {name: 'Blog', link: 'blog.html'}
  - {name: 'GitHub', link: 'https://github.com/jy0000'}
```

**Comment by PandaSekh** [comment]
I haven't worked with Jekyll for a while so I don't remember everything. Also, I didn't totally understand your issue, it's quite confusing. I'll focus on the icon issue.
In `sidebar.html` icons are rendered as: `<i class="fab fa-{{item.icon}}"` or `<i class="fas fa-{{item.icon}}"` depending on the type. However, it seems like LinkedIn is neither of them (it should be `fa fa-linkedin-in`).  
I released `1.0.2` which gives the option to not define a type to use `fa`. So the code should be:
`{icon: 'linkedin', type: "", link: ""}`
