### ISSUE TITLE
Translate Preview Text Continue link from Italian to English

### ISSUE THREAD

**Issue by krionical** [PandaSekh/Jekyll-Podcaster#3]
For each post there is a brief description of the episode. Following that description, there is a link that you click to continue. The link currently states the Italian version of continue and I'd like to change it to English, but I am having trouble locating where the code does this.

**Comment by PandaSekh** [comment]
Fixed. It was in `_layouts/home.html` lines 47 and 58

**Comment by krionical** [comment]
heh heh. Yeah, out of all the stuff I checked, I didn't check home. Thanks for getting on it. I like the work you have done on this project.

**Comment by PandaSekh** [comment]
Thank you!
