### ISSUE TITLE
Favicon Changing?

### ISSUE THREAD

**Issue by krionical** [PandaSekh/Jekyll-Podcaster#4]
Loaded a new favicon into root directory. Slightly bigger 16x16. Overwrote existing favicon.ico file but website appears to not reflect change.

**Comment by PandaSekh** [comment]
It's working for me. Check these: 
- The name has to be `favicon.ico`
- You have to re-build the project (hot-reload won't change the favicon)

If it still doesn't work, please post here the output of the command line

**Comment by krionical** [comment]
Command I am using to rebuild is: bundle exec jekyll serve   I assume this is the correct rebuild command? No errors generated by command line:

Configuration file: /home/joebs/Jekyll-Podcaster/_config.yml
            Source: /home/joebs/Jekyll-Podcaster
       Destination: /home/joebs/Jekyll-Podcaster/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.115 seconds.
 Auto-regeneration: enabled for '/home/joebs/Jekyll-Podcaster'
    Server address: http://127.0.0.1:4000//

Icon still the same in firefox. 

Edit: Name is correct.

**Comment by krionical** [comment]
Apparently, it is a firefox only issue. Chromium renders as expected. Not sure if you want to mark this closed or not.

**Comment by krionical** [comment]
After firefox update, issue resolved. Not a bug in your code--bug in firefox cache update.
