### ISSUE TITLE
Sidebar links "Where to Listen"

### ISSUE THREAD

**Issue by krionical** [PandaSekh/Jekyll-Podcaster#5]
External links do not appear to be populating list in sidebar under the heading "Where to Listen".

**Comment by PandaSekh** [comment]
Checked and it's working. You have to write them in the `settings.yml` file, under the variable `websites-podcast`. You have to write them in this format:    
`  - {name: 'Text shown in the list', link: 'actual url'}`

**Comment by krionical** [comment]
Yeah, I have that format right. It isn't working for me in either firefox or chromium. Is there some other setting that would affect the include for loop out of siderbar.html that I might have missed?

**Comment by PandaSekh** [comment]
No, it works without touching anything else. Have you modified this file: `/_includes/sidebar.html` ?

**Comment by krionical** [comment]
Here is sidebar:     <img src="{{"assets/img/Podcast_Cover_500.jpg" | absolute_url}}" alt="Podcast Cover">

<div id = "info">
    <h3>{{site.title}}</h3>
    <h4><i>{{site.description}}</i></h4>
</div>
<div id = "social">
    {% for item in site.data.settings.social %}
    {% if item.type == "brand"%}
      <a href="{{ item.link }}" target="_blank" id="{{item.icon}}"><i class="fab fa-{{item.icon}}" aria-hidden="true"></i></a>
    {% endif %}
    {% if item.type == "solid"%}
      <a href="{{ item.link }}" target="_blank" id="{{item.icon}}"><i class="fas fa-{{item.icon}}" aria-hidden="true"></i></a>
    {% endif %} 
  {% endfor %}
</div>
<div id = "ascoltare">
    <h3>Where To Listen</h3>
    <div id = "lista-siti">
        <ul id = "siti">
          {% for item in site.data.settings.websites-podcast  %}
          <li><a href="{{ item.url | absolute_url}}"> {{ item.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
</div>


Here is settings:

analytics-id: 
#Pages
pages:
  - {name: 'Episodes', url: 'episodes.html'}
  - {name: 'Donate', url: 'https://liberapay.com/NearlySacred/donate'}
  - {name: 'Shop', url: 'https://www.etsy.com/shop/MajiMarket'}
  - {name: 'Books', url: 'https://www.jbschirtzingerstore.com/'}
    #  - {name: 'Get This Theme', url: 'https://github.com/PandaSekh/Jekyll-Podcaster'}

social:
  - {icon: 'instagram', type: "brand", link: '#'}
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/ArteLettura'}
  - {icon: 'facebook', type: "brand", link: '#'}
  - {icon: 'youtube', type: "brand", link: '#'}  
  - {icon: 'envelope', type: "solid", link: 'mailto:jbschirtzinger@theroyalrainbow.com'}
  - {icon: 'rss', type: "solid", link: "#"}

websites-podcast:
  - {name: 'Apple Podcast', link: '#'}
  - {name: 'Spotify', link: 'https://open.spotify.com/show/5Q1iQgCWJOtzxD3KjGegjb'}
  - {name: 'YouTube', link: '#'}
  - {name: 'Android', link: '#'}
  - {name: 'Spreaker', link: '#'}
  - {name: 'Google Podcast', link: '#'}
  - {name: 'Anchor', link: 'https://anchor.fm/jb-schirtzinger'}
  - {name: 'Castbox', link: '#'}
  - {name: 'Overcast', link: '#'}
  - {name: 'RadioPublic', link: '#'}
  - {name: 'Breaker', link: '#'}  
  - {name: 'RSS', link: '#'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname: 


Do you see anything obviously wrong?

**Comment by krionical** [comment]
Here is sidebar: `<img src="{{"assets/img/Podcast_Cover_500.jpg" | absolute_url}}" alt="Podcast Cover">

<div id = "info">
    <h3>{{site.title}}</h3>
    <h4><i>{{site.description}}</i></h4>
</div>
<div id = "social">
    {% for item in site.data.settings.social %}
    {% if item.type == "brand"%}
      <a href="{{ item.link }}" target="_blank" id="{{item.icon}}"><i class="fab fa-{{item.icon}}" aria-hidden="true"></i></a>
    {% endif %}
    {% if item.type == "solid"%}
      <a href="{{ item.link }}" target="_blank" id="{{item.icon}}"><i class="fas fa-{{item.icon}}" aria-hidden="true"></i></a>
    {% endif %} 
  {% endfor %}
</div>
<div id = "ascoltare">
    <h3>Where To Listen</h3>
    <div id = "lista-siti">
        <ul id = "siti">
          {% for item in site.data.settings.websites-podcast  %}
          <li><a href="{{ item.url | absolute_url}}"> {{ item.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
</div>`

Here is settings: `analytics-id: 
#Pages
pages:
  - {name: 'Episodes', url: 'episodes.html'}
  - {name: 'Donate', url: 'https://liberapay.com/NearlySacred/donate'}
  - {name: 'Shop', url: 'https://www.etsy.com/shop/MajiMarket'}
  - {name: 'Books', url: 'https://www.jbschirtzingerstore.com/'}
    #  - {name: 'Get This Theme', url: 'https://github.com/PandaSekh/Jekyll-Podcaster'}

social:
  - {icon: 'instagram', type: "brand", link: '#'}
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/ArteLettura'}
  - {icon: 'facebook', type: "brand", link: '#'}
  - {icon: 'youtube', type: "brand", link: '#'}  
  - {icon: 'envelope', type: "solid", link: 'mailto:jbschirtzinger@theroyalrainbow.com'}
  - {icon: 'rss', type: "solid", link: "#"}

websites-podcast:
  - {name: 'Apple Podcast', link: '#'}
  - {name: 'Spotify', link: 'https://open.spotify.com/show/5Q1iQgCWJOtzxD3KjGegjb'}
  - {name: 'YouTube', link: '#'}
  - {name: 'Android', link: '#'}
  - {name: 'Spreaker', link: '#'}
  - {name: 'Google Podcast', link: '#'}
  - {name: 'Anchor', link: 'https://anchor.fm/jb-schirtzinger'}
  - {name: 'Castbox', link: '#'}
  - {name: 'Overcast', link: '#'}
  - {name: 'RadioPublic', link: '#'}
  - {name: 'Breaker', link: '#'}  
  - {name: 'RSS', link: '#'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname: 
`

Do you see anything obviously wrong? I haven't modified anything that I know of except I played with some spacing in the for loop trying to get the links to populate. I changed that back.

**Comment by PandaSekh** [comment]
No, i don't see anything wrong. I'm sorry but I don't know what the problem might be

**Comment by PandaSekh** [comment]
No, i don't see anything wrong. I'm sorry but I don't know what the problem might be

**Comment by krionical** [comment]
Well that's bad news for me. I'll keep poking about and see if I can figure out why the expected behavior is not occurring.

**Comment by krionical** [comment]
All right so I changed the loop a little: 

> <div id = "ascoltare">
    <h3>Where To Listen</h3>
    <div id = "lista-siti">
        <ul id = "siti">
          {% for item in site.data.settings.websites-podcast  %}
          <li><a href="{{ item.link}}"> {{ item.name }}</a></li>
          {% endfor %}

That solved the problem I was having with it. I'm not sure if that's something you want to do as a patch or not since you mentioned it is working for you.

**Comment by PandaSekh** [comment]
Well, that's identical to how it's done right now:
```
    <h3>Where To Listen</h3>
    <div id = "lista-siti">
        <ul id = "siti">
          {% for item in site.data.settings.websites-podcast  %}
          <li><a href="{{ item.url | absolute_url}}"> {{ item.name }}</a></li>
          {% endfor %}
        </ul>
    </div>
```

Maybe I didn't read your code correctly before

**Comment by krionical** [comment]
The pipe in a href somehow was causing it trouble. I changed that to item.link.

**Comment by dtenenba** [comment]
I had the same issue. Changing `item.url` to `item.link` in `_data/settings.yml` made it work for me.
