### ISSUE TITLE
posts did not display on home page

### ISSUE THREAD

**Issue by dtenenba** [PandaSekh/Jekyll-Podcaster#6]
I had to change 

```
{% for post in paginator.posts %}

```

to

```
{% for post in site.posts %}
```

in `home.html`.

**Comment by PandaSekh** [comment]
Paginator is used to paginate posts and is working as expected on the demo website.

**Comment by dtenenba** [comment]
So I thought the problem was that I did not have 'jekyll-paginate` in my `Gemfile`, (because the documentation does not say to add it)  but I added it and installed it and still have this problem. Is there some other dependency I need in order to get this to work? Thanks.

**Comment by dtenenba** [comment]
I started over by just cloning your repo instead of unzipping the release zip over my existing files (without overwriting any pre-existing files) and this worked....

**Comment by PandaSekh** [comment]
I probably need to update the release zip. Thanks for letting me know

**Comment by dtenenba** [comment]
I think the problem was not your release zip but the way I unzipped it over an existing jekyll site without overwriting existing files (Gemfile, etc).
