### ISSUE TITLE
Incorrect licence classification at MIT License

### ISSUE THREAD

**Issue by tfoote** [PandaSekh/Jekyll-Podcaster#9]
The license is incorrectly titled as "The MIT License". https://github.com/PandaSekh/Jekyll-Podcaster/blob/d4badee57ddcd000a858b314d1f26cb17802bed1/LICENSE.txt#L1

The license is the MIT license as per [Choose A License](https://choosealicense.com/licenses/mit/) or the [OSI](https://opensource.org/licenses/MIT) but with an additional clause. The means that it is no longer the OSI approved MIT license which the license title implies. 

https://github.com/PandaSekh/Jekyll-Podcaster/blob/d4badee57ddcd000a858b314d1f26cb17802bed1/LICENSE.txt#L12

The additional clause significantly changes the license in a non-trivial way and as such should no longer be called "The MIT License"

I originally downloaded this theme assuming that it was under the MIT license, however I just happened to read the LICENSE in full and upon reading the LICENSE file I found out that the terms were different than the MIT license. I was surprised that the terms of the LICENSE are not compatible with my expectations of the standard MIT license and that I will need to replace the theme for my current plans. I would like to not have others experience this same discontinuity.

I would suggest reclassifying the license as "A custom modified MIT license" or changing the project to use the standard MIT license.

**Comment by PandaSekh** [comment]
Updated #10

**Comment by tfoote** [comment]
Thanks for the quick resolution.
